### ISSUE TITLE
add flag to relay validity of target ray space

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#112]
Currently the Oculus browser doesn't populate the target ray space if it believes that a system gesture might happen.
This behavior triggers each time the user's hands are palms up.

I removed that behavior so the target ray is always sent but was wonder if this is a flag that we should forward to the author. This is how it's done in OpenXR (See `XR_HAND_TRACKING_AIM_VALID_BIT_FB` in https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_FB_hand_tracking_aim).

**Comment by Manishearth** [comment]
Hmmm. I think it would be possible to add gesture types but I'm not sure if there's standardization on gestures across systems just yet.

**Comment by cabanier** [comment]
/agenda indicate validity of target ray space

**Comment by thetuvix** [comment]
When HoloLens 2 ends up in that state (a given hand is "captured" by system UX), the entire `XRInputSource` stops enumerating.  Do you continue to give out grip poses during the period in which you would want the app to stop doing far-targeting with that hand?

**Comment by cabanier** [comment]
We do not stop handing out poses

**Comment by toji** [comment]
Discussed this on an editors call today. It's not clear what developers would do with such a flag, and the couple of examples I came up with were antipatterns that we wouldn't want to encourage. As such I'd suggest holding off on adding it to WebXR unless we hear some compelling use cases for it.

In the meantime, it sounds like the Oculus browser has done some work to smooth over any issues developers might have had with the target ray unexpectedly disappearing.
