### ISSUE TITLE
Add a 'hand scale'

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#19]
The Oculus API has a scale factor for the hands.
(See line 666 in https://developer.oculus.com/reference/mobile/v14/vr_api_input_8h/)

This allows that author to use a standard hand model, animate it and then apply a scale so it matches the user's hand size.

Can we add a similar concept to the WebXR Hands API?

**Comment by Manishearth** [comment]
We'd have to standardize a hand model to do this, no? This sounds useful but I'm also not quite sure how to specify it

**Comment by cabanier** [comment]
I'm unsure if it's necessary to standardize on a model. 
It does seem that we'd need to standardize the size of the average hand.

**Comment by Manishearth** [comment]
Right, that's what I mean

**Comment by cabanier** [comment]
I think we can address hand scale at a future point.
