### ISSUE TITLE
Why is radius optional?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#23]
The IDL shows that the radius attribute can be nullable but it doesn't specify what a null radius implies. 
One reasonable approach is to say that the attribute returns null when radius tracking is not supported on that joint. If radius tracking is supported but the radius is not currently tracked, then the attribute can return zero. 
This would parallel the joint space approach where the getter returns null when joint tracking is not supported on that joint, and returns a non null joint space that generates null poses when not tracked.

**Comment by Manishearth** [comment]
Yes, this is the intent: "I know where the joint is but I don't have its radius", i.e. radius tracking is not supported

**Comment by cabanier** [comment]
What should the author do if the joint radius is not known?
Also, will it be allowed if the radius comes and goes between frames?

**Comment by Manishearth** [comment]
The author can use an approximate value as a guess.

I'd like to say that UAs aren't allowed to change that between frames, but there may be devices where that happens? Seems unlikely. I dunno, in that case we can also ask the UA to cache the value

**Comment by Manishearth** [comment]
From discussion in today's meeting, it seems like we should probably make the radius mandatory (and ask UAs to pick an emulated value if they do not have it).

cc @thetuvix @toji
