### ISSUE TITLE
Should we create a spec?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#25]
Now that hands is implemented by 2 UA's, should we create a specification and push it towards rec?

**Comment by Manishearth** [comment]
Yeah I'm working on a draft, but it's been low priority. If y'all have it implemented and are interested in pushing it forward, that definitely bumps the priority for me! I'll try to get to it.

**Comment by cabanier** [comment]
Let me know if you want help.

**Comment by Manishearth** [comment]
@AdaRoseCannon @cwilso is it okay if I rename this repo to webxr-hand-input? The plural is confusing.

**Comment by cwilso** [comment]
SGTM

**Comment by Manishearth** [comment]
Renamed, and I landed a bikeshed spec.

https://github.com/immersive-web/webxr-hand-input/pull/26

I need someone to set up the travis autodeploy.

**Comment by Manishearth** [comment]
@AdaRoseCannon Could you add the appropriate github token to https://travis-ci.org/github/immersive-web/webxr-hand-input/settings ? I'm not sure what we use there.

**Comment by AdaRoseCannon** [comment]
I haven't done it before but gonna find out how

**Comment by Manishearth** [comment]
Oh, then who was setting those up before? Otherwise I can do this with Actions, they set up deploy tokens automatically

**Comment by cabanier** [comment]
I believe @toji set it up for Layers

**Comment by Manishearth** [comment]
Ah. Either way, I've got it mostly working with Actions already

**Comment by Manishearth** [comment]
https://immersive-web.github.io/webxr-hand-input/

**Comment by AdaRoseCannon** [comment]
Travis is done!

**Comment by AdaRoseCannon** [comment]
```
rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl

invalid option "--token="

failed to deploy
```

**Comment by Manishearth** [comment]
@AdaRoseCannon yeah i got the same issue. But it's fine, I set it up with Actions instead and it was easier -- no tokens needed!
