### ISSUE TITLE
Move into the WG

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#33]
We now have two conforming implementations of this API shipped behind a pref (FxR on Hololens 2 and Oculus Browser on the Quest). Overall the core API is probably not going to change much, though we may add some new features and there's room for a lot of polish.

So it seems to me like this is a good opportunity to move this into the WG.

**Comment by Manishearth** [comment]
cc @AdaRoseCannon @Yonet @cwilso

**Comment by Manishearth** [comment]
/agenda To be discussed in the WG meeting

**Comment by himorin** [comment]
concluded at https://www.w3.org/2020/08/04-immersive-web-minutes.html#item01 (right?)
