### ISSUE TITLE
Radius discrepancies between platforms

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#34]
Here's an image of all the hand joints on Firefox Reality on Hololens 2 (ignore the offset with the background, secondary views were not enabled):

![image](https://user-images.githubusercontent.com/1617736/88581552-31120d00-d002-11ea-8ca1-0adcab7ea28e.png)

Here is an image of the same on Oculus Browser
![image](https://user-images.githubusercontent.com/1617736/88581587-3d966580-d002-11ea-9885-c22c114e4771.png)

Now, not all joints are supported in Oculus, but it's worth noting that the pinky metacarpal joint is supported in both and has a wildly different size. I believe both APIs are trying to model "distance to skin", so it feels like they should be the same size.

This might cause issues when skinning these joints in a cross-platform way. I think it's worth figuring out what the discrepancy is.

cc @thetuvix @cabanier

**Comment by cabanier** [comment]
Can you create a table with the radius values of each?
Also, you're using different sites in your screenshot. Can you use the same one?

**Comment by Manishearth** [comment]
Yeah the second screenshot is from Fernando's work, I currently don't have time to gather more data or run more tests but I wanted to have this on file. I'll try to get something soon.

**Comment by cabanier** [comment]
@Manishearth should we close this issue? It seems that both platforms are rendering hands correctly.
