### ISSUE TITLE
Have a joint set object that lets you fetch all joint poses at once

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#37]
During discussion of https://github.com/immersive-web/webxr-hand-input/pull/32 in today's call it seemed like while everyone wanted to solve the problem of ~200 objects being created per frame, folks didn't want to cache XRJointPoses because it would be unexpected.

[OpenXR's API for this](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#xrLocateHandJointsEXT) returns a single object containing all joint pose info. We could do something similar.

We wish to keep the joint spaces because it's useful to be able to relate them with each other via `getPose()`, but it would be nice if there were some "all hand joints" object that could be accessed for efficiency.

I'm imagining an API like:

```webidl
interface XRAllJoints {
   constructor(XRHand hand, XRSpace baseSpace);
   void populatePoses(XRframe frame);
   DOMPointgetPosition(unsigned int id);
   DOMPoint getOrientation(unsigned int id);
   Float32Array getTransform(unsigned int id);
   float getRadius(unsigned int id);
}
```

cc @cabanier @thetuvix @toji

**Comment by cabanier** [comment]
Is `transform` needed? It seems a UA can calculate it from `position` and `orientation`

> void populatePoses(XRframe frame);

We probably should also pass `XRHand` here.

**Comment by Manishearth** [comment]
> Is `transform` needed? It seems a UA can calculate it from `position` and `orientation`

Right, we'll calculate it for the user, the same way we do for XRRigidTransform. It can be lazily populated.

> We probably should also pass `XRHand` here.

Nah that should be in the constructor

**Comment by cabanier** [comment]
> > Is `transform` needed? It seems a UA can calculate it from `position` and `orientation`
> 
> Right, we'll calculate it for the user, the same way we do for XRRigidTransform. It can be lazily populated.

The conversion is so easy; we shouldn't add this to the API.

> > We probably should also pass `XRHand` here.
> 
> Nah that should be in the constructor

Yes, you're right :-)

**Comment by Manishearth** [comment]
I find it weird that we would return transforms in XRPose but not here, and also would like to avoid people calling `new XRRigidTransform(pos, orient).transform`

**Comment by Manishearth** [comment]
A thing to note: my current API does not reduce the JS-system traffic much. If we wish to do that we'd probably have to introduce a way to get large frozen arrays wholesale from the API.

**Comment by Maksims** [comment]
Low level solution would be providing something like Float32Array to API, which would populate it with interleaved data. But that of course would be something "non-weby", although highest performance and allocation-free:

```javascript
interface XRAllJoints {
   constructor(XRHand hand, XRSpace baseSpace);
   void getPositions(XRframe frame, Float32Array data);
   void getOrientations(XRframe frame, Float32Array data);
   ...
}
```

Regarding `transform`, it is interesting to see if people use it, or actually use position and orientation instead. Especially how does this relates to engines with different coordinate systems, do they first modify position/orientation and then construct transform or they take transform and flip it by axes?

**Comment by cabanier** [comment]
Could we further simplify this with just a call on XRFrame:
```webidl
partial interface XRFrame {
  bool getjointPoses(XRHand hand, XRSpace baseSpace, Float32Array positions, Float32Array orientations);
}
```

**Comment by Manishearth** [comment]
You'd want radii as well. But yes, we could do that. It feels less webby but we do have a webby API too.

I think frameworks are not going to be using the flat arrays as flat arrays, though.

**Comment by cabanier** [comment]
If you use `DOMPoint` each attribute access is a trip to c++ so that's a bit expensive as well.

> we do have a webby API too.

yes.

**Comment by toji** [comment]
I'm not sure if I understand the motivation behind this returning position/orientation/transform separately instead of `XRRigidTransform`s? Then the question of whether or not matricies are included becomes moot. (Also, I'm not a fan of the idea that `transform` everywhere else means `XRRigidTransform` and here it means a matrix.) 

> Could we further simplify this with just a call on XRFrame..

Yeah, Rik's snippet is a bit more what I had in mind when I brought this up on the call. I was actually wondering about taking it a step further and allowing this variant to be used for ANY spaces, like so:

```webidl
partial interface XRFrame {
  bool getPoses(sequence<XRSpace> spaces, XRSpace baseSpace, Float32Array positions, Float32Array orientations);
}
```

At which point I could use this for everything but the viewer pose if I wanted. Coincidentally, since the hand is just an enumerable list of joint spaces it would still work to simply do this:

```js
frame.getPoses(inputSource.hand, referenceSpace, outPositions, outOrientations);
```

> Regarding transform, it is interesting to see if people use it, or actually use position and orientation instead.

I know that at least Three.js uses transform matrices directly.

**Comment by Manishearth** [comment]
> I'm not sure if I understand the motivation behind this returning position/orientation/transform separately instead of `XRRigidTransform`s

We can't! XRRigidTransforms contain DOMPointReadOnlys, so suddenly we have a way of modifying them, which is ... bad. What would happen if I took one of these transforms and slapped it into `getOffsetReferenceSpace()`? 😄 

> Yeah, Rik's snippet is a bit more what I had in mind when I brought this up on the call. I was actually wondering about taking it a step further and allowing this variant to be used for ANY spaces, like so:

I felt that having a single output object would be very useful here. We could even give it _both_ APIs with a DomPoint getter and a Float32Array attribute for each thing, and lazy initialization would mean these only get updated when you need them.

**Comment by cabanier** [comment]
> ```webidl
> partial interface XRFrame {
>   bool getPoses(sequence<XRSpace> spaces, XRSpace baseSpace, Float32Array positions, 
>                 Float32Array orientations);
> }
> ```

I like that one! This way authors can efficiently get a subsection. 
We do want to pass `XRJointSpaces` though and return `radii`.

**Comment by cabanier** [comment]
> > Yeah, Rik's snippet is a bit more what I had in mind when I brought this up on the call. I was actually wondering about taking it a step further and allowing this variant to be used for ANY spaces, like so:
> 
> I felt that having a single output object would be very useful here. We could even give it _both_ APIs with a DomPoint getter and a Float32Array attribute for each thing, and lazy initialization would mean these only get updated when you need them.

If we can avoid it, we should not introduce new objects.
It's also an additional burden on developers because now they have to keep track of an additional helper object.

**Comment by cabanier** [comment]
What do framework authors think? @Maksims @mrdoob @dmarcos
Should we have a single object `XRAllJoints` that manages the poses, or a single API call on `XRFrame` that returns separate arrays to describe the poses.

**Comment by Manishearth** [comment]
cc @raananw too

**Comment by Manishearth** [comment]
To be clear, my current proposal is

```
interface XRAllJoints {
   constructor(XRHand hand); // can also be a method on XRHand

   // Attributes for directly feeding to the GPU
   attribute readonly Float32Array positions;
   attribute readonly Float32Array orientations;
   attribute readonly Float32Array radii;

   // Getters for feeding into, e.g. ThreeJS object metadata
   DOMPoint getPosition(unsigned int id);
   DOMPoint getOrientation(unsigned int id);
   Float32Array getTransform(unsigned int id);
   float getRadius(unsigned int id);
}

partial interface XRFrame {
   void populatePoses(XRAllJoints joints, XRSpace baseSpace);
}
```


You would use the API like this:

```js

// at the beginning of the session
let leftJoints = new XRAllJoints(leftInput.hand);

// each frame
frame.populatePoses(leftJoints, localSpace);

for (i = 0; i < number_of_joints; i++) {
   leftModel.joints[i].transform = leftJoints[i].transform;
   leftModel.joints[i].radius = leftJoints[i].radius;
}

// render leftModel
```

**Comment by dmarcos** [comment]
No strong opinions on one function per joint vs. retrieve all joints at once. Whatever protects the most against allocations / GC pauses. Maybe I just expect consistency with other parts of the spec. A-Frame uses [transform.matrix](https://github.com/aframevr/aframe/pull/4652/files#diff-9becd78739a201d3e60b200e83531abcR108) for both joints and head pose. Good work everybody.

**Comment by Manishearth** [comment]
@Maksims This is not for multiple input sources at one go, this is for one XRHand at a time, and each XRHand is tied to an input source. This is true in both my proposed API (where `XRAllJoints` is constructed from an `XRHand`) and @cabanier's (where `getJointPoses()` accepts an `XRHand`)

>  Also should it return true/false when it did populated information or not, based on tracking state?

Yeah this is also why I prefer the XRAllJoints approach, because each getter can return null if it wishes.

It's worth figuring out (separately, in https://github.com/immersive-web/webxr-hand-input/issues/36) if we want to make it so that either the entire hand is reported or none of it is. In that case the API you and @cabanier proposed (in https://github.com/immersive-web/webxr-hand-input/issues/37#issuecomment-665720921) would work, but I still prefer having a separate object.

**Comment by cabanier** [comment]
> > Also should it return true/false when it did populated information or not, based on tracking state?
> 
> Yeah this is also why I prefer the XRAllJoints approach, because each getter can return null if it wishes.

`XRAllJoints` feels a bit heavyweight. I'd much prefer if we could get by with a couple of function calls.

Thinking about this some more, we might be able to simplify the spec quite a bit.
For instance, the `radius` is not relative to another `XRSpace` so there's no real reason to require a baseSpace.
This means that `XRJointPose`and thus `getJointPose` are not really needed and could be dropped and we could get by with the regular `getPose`.

The interface could look like this:
```webidl
partial interface XRFrame {
 float? getJointRadius(XRJointSpace joint); // replaces getJointPose

  // for bulk operations
 bool getPoses(sequence<XRSpace> spaces, XRSpace baseSpace, Float32Array positions, Float32Array orientations);
 bool getJointRadii(sequence<XRJointSpace> spaces, Float32Array radii);
};
```

`getPoses` could move to the WebXR spec since it's not specific to hands.
We might even be able to get rid of `XRJointSpace`. We might also consider using a sequence of `DOMPointInit` instead of `Float32Array` but then each access will cross the c++ boundary.

You would use the API like this:

```js
  // each frame
  if (frame.getPoses(leftJoints, localSpace, leftModel.joints.positions, leftModel.joints.orientations) 
    && frame.getJointRadii(leftJoints, leftModel.joints.radii) {
    // render hand;
  } else {
    // remove hand
  }
 ```

**Comment by Manishearth** [comment]
> ```webidl
>  bool getPoses(sequence<XRSpace> spaces, XRSpace baseSpace, Float32Array positions, Float32Array orientations);
> ```

How does this work with tracking loss, though? Another array of bools?

**Comment by cabanier** [comment]
> > ```webidl
> >  bool getPoses(sequence<XRSpace> spaces, XRSpace baseSpace, Float32Array positions, Float32Array orientations);
> > ```
> 
> How does this work with tracking loss, though? Another array of bools?

At least for Oculus, poses have an all or nothing success rate so a simple bool return suffices. For UA's that can do partial hand results, they could put NaN's as return values.

**Comment by Manishearth** [comment]
> At least for Oculus, poses have an all or nothing success rate so a simple bool return suffices. For UA's that can do partial hand results, they could put NaN's as return values.

Well, the array is not just XRJointSpaces 😄 . This is kinda why I want to focus on joints and do this "for the entire hand", because OpenXR is also all-or-nothing here.

**Comment by cabanier** [comment]
> Well, the array is not just XRJointSpaces 😄 . This is kinda why I want to focus on joints and do this "for the entire hand", because OpenXR is also all-or-nothing here.

Ok, then we could define it as "if there is tracking loss, try to return an emulated value. If an emulated value can't be returned, return NaN:

**Comment by Manishearth** [comment]
Yeah, but this is kinda why I prefer the AllJoints model, because we can do _both_: consumers who wish to pass data to the GPU can use the arrays, consumers who want DOMPoints can check the DOMPoints. There's some JS-native traffic there but the main  goal is fixing allocations IMO.

I'm not against `getPoses()`, though. I just find it potentially unnecessary. An advantage of that model is that you can pick and choose what you want: if you want positions, you can ask for positions, if you want transforms you can ask for transforms (and null out the others).

Perhaps we should have something like this instead?

```webidl
dictionary FillPoses {
   Float32Array? positions;
   Float32Array? orientations;
   Float32Array? transforms;
}


interface XRFrame {
   void fillPoses(sequence<XRSpace> spaces, XRSpace base, FillPoses poses)
}
```

The advantage here is that it can be called as `fillPoses(spaces, base, {transforms: transforms})` or `fillPoses(spaces, base, {positions: positions, orientations: orientations})` per preferences and you don't have to pass in nulls,

Idk, I'm not a fan of passing a million parameters to a function 😄

**Comment by cabanier** [comment]
> 
> Perhaps we should have something like this instead?
> 
> ```webidl
> dictionary FillPoses {
>    Float32Array? positions;
>    Float32Array? orientations;
>    Float32Array? transforms;
> }
> 
> 
> interface XRFrame {
>    void fillPoses(sequence<XRSpace> spaces, XRSpace base, FillPoses poses)
> }
> ```

That's a neat idea. Do you know of any APIs on the web platform that use this idiom? (= pass optional parameters in a dictionary that are filled in by the call)

> Idk, I'm not a fan of passing a million parameters to a function 😄

I agree it's not as pretty but it does save on typing.

**Comment by Manishearth** [comment]
Not aware of any APIs that do this.

I'm not sure it saves on typing, it's quite likely that the frameworks will be stashing `positions` `orientations` and `transforms` somewhere _anyway_

**Comment by cabanier** [comment]
> Not aware of any APIs that do this.

Well... then we probably shouldn't do it :-(

> I'm not sure it saves on typing, it's quite likely that the frameworks will be stashing `positions` `orientations` and `transforms` somewhere _anyway_

```js
fillPoses(spaces, base, positions, orientations);
``` 
is shorter than
```js
fillPoses(spaces, base, {positions: positions, orientations: orientations});
```

**Comment by Manishearth** [comment]
I believe you can just write `{positions, orientations}` but more specifically I'd expect people to have these around in an object anyway

Either way, unsure if this is good

**Comment by Maksims** [comment]
> ```js
> fillPoses(spaces, base, positions, orientations);
> ```
> 
> 
> is shorter than
> ```js
> fillPoses(spaces, base, {positions: positions, orientations: orientations});
> ```
First option does not allow extra arguments, like "radius" or "transforms", while second option gives you ability to extend object with keys, depending on available data.

This is actually very generic, gives you ability to query transforms for gripSpace:
```js
let data = { transforms: transformsData };
frame.fillPoses([ inputSource.gripSpace ], referenceSpace, data);
```

As well as joints data:
```js
let data = { orientations: orientationData, positions: positionsData, radii: radiiData };
frame.fillPoses(handJoints, referenceSpace, data); 
```

This suits engines which use transform or position+orientation, as well as any extra data, like radius of joints.
No allocations, no null arguments, pretty clean and self explanatory.

The only thing that documentation has to clarify, is how many floats are used per item, like transformations are mat4x4, so 16 floats, positions are 3 floats, orientations are 4 floats, radius is 1 float.
So developer has to create Float32Array with no less data than that.

**Comment by RaananW** [comment]
Looking at the current API (in other modules and WebXR itself), `frame.getHandPose` (or `Poses`) feels much more consistent. Same goes to sticking with XRRigidTransforms (which is used throughout the API) and not positions/rotation/matrices. 

The simplest approach i could think of was this - 

```javascript
interface XRFrame {
  FrozenArray<XRJointPose> getJointPoses(XRHand hand, XRSpace referenceSpace);
  // while keeping the current API for specific joint queries
  XRJointPose getJointPose(XRJointSpace joint, XRSpace relativeTo);
}
```

This will return poses for a single hand (and not both at the same time), but will not require calling the getJointPose API 20 times. 

A different approach - similar to `getViewerPose`, we could also get an already populated XRHand Set with the relevant information. something like this:

```javascript
interface XRFrame {
  FrozenArray<XRHand> getHandPoses(XRSpace referenceSpace);
}
```

which will require two changes - a different reference in the XRInputSource (`xrInput.hand` is no longer XRHand, but an index or some form of a placeholder that can be associated with the `XRHand` object), and that the XRHand object will not contain `XRSpace` but `XRPose` objects.

**Comment by Manishearth** [comment]
> This will return poses for a single hand (and not both at the same time), but will not require calling the getJointPose API 20 times.

@RaananW Unfortunately this does not satisfy the requirements, the primary issue at hand is not that you have to call `getJointPose()` 20 times, it is that each frame the user agent must allocate 25 x 2 XRJointPoses (which is also 50 XRRigidTransforms and 100 DOMPointReadOnly). It's not possible to reuse the XRRigidTransforms since they're assumed to be immutable, and furthermore we expect XRPose to be something the author may wish to hold on to at times.

**Comment by RaananW** [comment]
Got it. But if we don't use XRRigitTransformation (or introduce XRMutableRigidTransformation), this can still be a single reusable object. Both suggestions actually.

**Comment by Manishearth** [comment]
@RaananW Yeah that's what my original API proposes

**Comment by Manishearth** [comment]
So I discussed this more with @toji and a couple things occurred to me:

Firstly, if we implement https://github.com/immersive-web/webxr-hand-input/issues/36 _and_ require devices report "all or none", we can turn `XRHand` into an iterable and can pass it in whenever `sequence<XRSpace>` is required.

Secondly, overloading is possible! We can have both these APIs at once:

```webidl
interface XRFrame {
    void getAllPoses(sequence<XRSpace> spaces, XRSpace base, Float32Array positions, Float32Array orientations);
    void getAllPoses(sequence<XRSpace> spaces, XRSpace base, Float32Array transforms);
}
```

Note, however, while we can have APIs that overload `sequence<>` the WebIDL overload resolution algorithm does not seem to be able to distinguish between `sequence<A>` and `sequence<B>`, and furthermore will not be able to distinguish between those and `Float32Array`; so we can only have one method per number of arguments.

We can also have a `getAllJointRadii(XRHand, Float32Array radii)` API that gets all joint radii at once.

I would kinda _prefer_ to have an API that works on DOMPoints but I understand the pushback.

**Comment by Maksims** [comment]
And how lost tracking will be handled? Fills Float32Arrays with NaN's? Or returns boolean (modified==true) and keeps arrays untouched?

**Comment by cabanier** [comment]
> And how lost tracking will be handled? Fills Float32Arrays with NaN's? Or returns boolean (modified==true) and keeps arrays untouched?

The functions would have to return a `bool`. I think @Manishearth forgot to add that since he said:

> require devices report "all or none"

**Comment by cabanier** [comment]
> I would kinda _prefer_ to have an API that works on DOMPoints but I understand the pushback.

Since these are low level APIs, I think it's ok for them to be less developer friendly in exchange for higher performance.

**Comment by Manishearth** [comment]
"all or none" works if this is a hand-specific API, but not if this is an API requesting multiple spaces in general IMO

But we can set NaN

**Comment by Manishearth** [comment]
TAG discussion at https://github.com/w3ctag/design-principles/issues/231

**Comment by toji** [comment]
I take it as a good sign that we're one of several groups asking about this, rather than the weird outlier. Interested to see what comes of it.

**Comment by cabanier** [comment]
@Manishearth Can you prepare a PR for this? If we wait too long, we might forget some details.

**Comment by Manishearth** [comment]
I think the issue is that there are two approaches. I can prepare a PR for both but I'm a bit busy today.

**Comment by cabanier** [comment]
I believe your proposal in https://github.com/immersive-web/webxr-hand-input/issues/37#issuecomment-667308534 is the least controversial one.

**Comment by thetuvix** [comment]
I'll likely need to join the call late today, though I'm very interested in this topic!  This exact bulk joint update API discussion was the last thing to converge in the OpenXR hand tracking discussions.

I am generally in favor of pushing on the "fill-array" style patterns here that TAG is warming up to, as we will need them even more strongly when we are returning mesh vertex/index buffers to apps.  I'm most in favor of @Manishearth's [original `XrAllJoints` proposal](https://github.com/immersive-web/webxr-hand-input/issues/37#issuecomment-665946699) over the generic `getPoses` approach, as I expect us to have related data to serve up here over time.  I could warm to the `getPoses` approach, so long as we find a solution to reasonably handle `emulatedPosition` and tracking loss, though I expect that will ultimately feel messier than bool attributes on an `XrAllJoints`-style type.

**Comment by Manishearth** [comment]
@thetuvix we're discussing this now

**Comment by thetuvix** [comment]
Sorry I couldn't make it to the call on Tuesday!

My primary concern with seemingly simpler approaches like https://github.com/immersive-web/webxr-hand-input/issues/37#issuecomment-667308534 is that I suspect the `getPoses` overload approach will become more complex than the [`XrAllJoints` proposal](https://github.com/immersive-web/webxr-hand-input/issues/37#issuecomment-665946699) once all the data values we need to communicate are represented. (e.g. `radius`, `isDetected`, `isEmulated`)

Here are the per-hand and per-joint values that the hand module will need to communicate each frame in some manner:
* **Per-hand:** (one per `XRInputSource`)
  * `isDetected` (if false, any per-joint array values should be ignored)
  * **Per-joint:** (array size known to app in advance, because app chose a specific joint set with well-known joints - see #36)
    * `position`/`orientation` (and/or `transform`)
    * `radius`
    * `isEmulated` (if true, this joint position/orientation is still usable, but the joint pose was occluded or otherwise inferred this frame relative to other nominally-tracked joints)
    * _Later:_ `linearVelocity`/`angularVelocity` (when we otherwise add `XRSpace`-relative velocity to the WebXR API)

The `XRAllJoints` approach gives us a natural place to hang both per-hand scalars and various per-joint arrays, including any additional arrays in the future for things like `linearVelocity`/`angularVelocity`.

Note that as part of #36, we're making the key simplification for developers that if they get any joints back (i.e. `isDetected` is true), they will get back a usable pose and radius for all joints in the joint set they requested, even if some joints have their `isEmulated` bool set to true this frame.

**Comment by Manishearth** [comment]
We did decide to land https://github.com/immersive-web/webxr-hand-input/issues/36 so the isDetected isn't needed anymore. isEmulated might be.

**Comment by cabanier** [comment]
> We did decide to land #36 so the isDetected isn't needed anymore. isEmulated might be.

I'm unsure what authors can do with `isEmulated`. I don't think we need it.

**Comment by toji** [comment]
Agreed that we probably don't need `isEmulated` unless developers are asking for it.  It's easy enough to add later.

**Comment by cabanier** [comment]
@toji Can I create a PR that adds these APIs?
There doesn't seem to be any feedback from the TAG on the design principle and we want to move forward.

**Comment by toji** [comment]
Yeah, it wouldn't hurt to have a concrete proposal. We can even point the TAG at it and point out "this is a pattern we think can work well. Do you have concerns?"

**Comment by thetuvix** [comment]
My understanding of #36 is that a hand is "all or nothing" - either you get all the joints or you get no joints.  That's a great improvement - is the idea then that when the left or right hand moves out of the detection FOV on the device, that entire `XRInputSource` then just does not enumerate?

**Comment by thetuvix** [comment]
I'm fine to leave out the per-joint `emulated` value if we don't see a strong use for it now.  Given that we need somewhere to hand the per-joint `radius` values, and to leave ourselves the easy place later to add per-joint `emulated` and `linearVelocity/angularVelocity` if we do get those requests, I'd still go the `XRAllJoints` direction for now.

**Comment by Manishearth** [comment]
@cabanier i intend to write a PR, but I haven't had a chance due to the ... whirlwind of last week 😄 

The plan that I and @toji had discussed was to have two APIs:

 - `bool fillPoses(sequence<XRSpace>, JointDict)`
 - `bool fillRadii(sequence<XRJointSpace>, Float32Array)`

Both would be in this specification. Yes, we have use cases out of this spec, but this is where it's most useful, and after incubating here we can uplift to a WebXR level 2 if the anchors folks like it too.

JointDict would start off with a single nullable `Float32Array transforms` field, but we can also add

 - isDetected for whether each space had a non-null pose
 - emulatedPosition (e.g. for when a joint is obscured)
 - velocity if that ever happens
 - we can even add radii if we really want

in the future

The boolean return value is `true` if any pose is non-null.

**Comment by Manishearth** [comment]
I think in our discussion we were also largely okay with having a `fillPoses(sequence, Float32Array transforms)`, with the idea that if we want to extend it we can just add another API

**Comment by cabanier** [comment]
> I think in our discussion we were also largely okay with having a `fillPoses(sequence, Float32Array transforms)`, with the idea that if we want to extend it we can just add another API

Yes, let's just add the minimal API we need. As you mention, we can always extend it later.

**Comment by cabanier** [comment]
> @cabanier i intend to write a PR, but I haven't had a chance due to the ... whirlwind of last week 😄 . Feel free to if you want to!
> 
> The plan that I and @toji had discussed was to have two APIs:
> ...
> * `bool fillRadii(sequence<XRJointSpace>, Float32Array)`

Can we call it `fillJointRadii`? Otherwise it's not clear (from the name) that this API only applies to joints.

**Comment by thetuvix** [comment]
> The plan that I and @toji had discussed was to have two APIs:
> 
> * `bool fillPoses(sequence<XRSpace>, JointDict)`
> * `bool fillRadii(sequence<XRJointSpace>, Float32Array)`

Are these sequences still required?  With #36, can we just fill the full set of joints?

**Comment by cabanier** [comment]
> > The plan that I and @toji had discussed was to have two APIs:
> > 
> > * `bool fillPoses(sequence<XRSpace>, JointDict)`
> > * `bool fillRadii(sequence<XRJointSpace>, Float32Array)`
> 
> Are these sequences still required? With #36, can we just fill the full set of joints?

This gives you the option of passing a subset of spaces as well as passing an XRHand object.

**Comment by cabanier** [comment]
What should happen if the size of the buffer is too small? Throw an exception?

**Comment by Manishearth** [comment]
Yes, in fact we can mandate that the buffer is exactly the size of the input iterable.

Alternatively we can fill it for the first n spaces.

**Comment by cabanier** [comment]
I prefer that it fills in the first n spaces.

**Comment by toji** [comment]
+1 for having it fill the first `n` spaces
