### ISSUE TITLE
Publish an FPWD

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#47]
We should publish an FPWD.

cc @himorin, i'm not sure what the steps are here.

**Comment by himorin** [comment]
we need to have Call for Consensus in WG (not CG as today's call; e.g. [one for gamepads](https://lists.w3.org/Archives/Public/public-immersive-web-wg/2019Sep/0011.html)), and I'll work on publication incl. request for transition and publication. 
after FPWD publication, editors/chairs are requested to perform: [horizontal review](https://w3c.github.io/documentreview/#how_to_get_horizontal_review), notice to chairs mail lists (for other working groups), and call for wide review to external liaison groups.

**Comment by Manishearth** [comment]
@cwilso would you be able to post the Call for Consensus? Unsure if it has to be a chair that does that.

I don't think we're _quite_ ready for horizontal review on all aspects -- in particular there's a fair amount of privacy/security work that needs to go in this, but once we have an FPWD we can start requesting _some_ review.

**Comment by Manishearth** [comment]
Filed https://github.com/immersive-web/webxr-hand-input/issues/50

**Comment by Manishearth** [comment]
Looks like we have been in WG since 7fa9b3f

**Comment by himorin** [comment]
closing this since FPWD has published. I'll file another issue on post-FPWD wide review tracking.
