### ISSUE TITLE
Move to WG

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#50]
cc @cabanier 

Moving to the WG will enable us to be REC-track (and move forward on https://github.com/immersive-web/webxr-hand-input/issues/47)

**Comment by Manishearth** [comment]
/agenda to notify people of our plans

**Comment by cabanier** [comment]
Didn't you already ask to move hands to the WG?

**Comment by Manishearth** [comment]
I recall wanting to, but I don't think a proper email was sent out

**Comment by himorin** [comment]
we had WG call as: https://www.w3.org/2020/08/04-immersive-web-minutes.html#item01, by https://github.com/immersive-web/webxr-hand-input/issues/33
and this repo was edited to be in WG by: https://github.com/immersive-web/webxr-hand-input/commit/7fa9b3f43e89b740d6def64276ab6dc6b640d14a

**Comment by AdaRoseCannon** [comment]
So no need for an email??

**Comment by Manishearth** [comment]
Nope, we just need one for FPWD
