### ISSUE TITLE
remove style.css?

### ISSUE THREAD

**Issue by himorin** [immersive-web/webxr-hand-input#56]
It seems contents of style.css are ones inserted to processed index.html by bikeshed, and also not used as external stylesheet in index.html nor not loaded during bikeshed processing.
Do we need this file in this repository?

**Comment by Manishearth** [comment]
I copied what the core spec does, I think it might be necessary for github pages to handle it correctly?

**Comment by himorin** [comment]
Ah,,, it seems this file came from WebVR repository, which had a directory as 'spec' for drafts, and style.css was used for top level web page but not for drafts. (actually, this file seems to be the same as what bikeshed inserts into index.html during their processing.)

https://github.com/immersive-web/webxr/commit/9f19295a067713d88e57aaea6ebbb7ab5914023f#diff-b78be019f1dc6d57753ea900c3805b114cd53ab7c0db836cc081836df1b99b7a
