### ISSUE TITLE
Should we require user consent to allow hand input?

### ISSUE THREAD

**Issue by fordacious** [immersive-web/webxr-hand-input#64]

**Comment by fordacious** [comment]
Up to the user agent how they handle feature descriptors.

**Comment by Manishearth** [comment]
Yeah, the status quo is that this requires the hand-input feature descriptor, and _most_ feature descriptors should involve consent at session initialization, however some (like secondary-views) may not.

We could call this out and strongly suggest that this involve consent.

**Comment by cabanier** [comment]
https://www.w3.org/TR/webxr-hand-input-1/#privacy-security calls out that consent MUST be asked before allowing hand input.
@Manishearth I think we can close this issue
