### ISSUE TITLE
Consider not using numeric constants

### ISSUE THREAD

**Issue by domenic** [immersive-web/webxr-hand-input#70]
The example uses `XRHand.THUMB_METACARPAL` and the IDL declares a bunch of similar constants.

However, numeric constants are generally bad practice on the web platform. See the warning at https://heycam.github.io/webidl/#idl-constants :

> Constants have in the past primarily been used to define named integer codes in the style of an enumeration. The Web platform is moving away from this design pattern in favor of the use of strings. Editors who wish to use this feature are strongly advised to discuss this by filing an issue before proceeding. 

As such, it'd be better to just use strings, e.g. `"thumb-metacarpal"`, `"wrist"`, etc.

**Comment by cabanier** [comment]
That is a fair point. There are indeed not many web APIs that define so many constants.

Are you proposing that we switch from constants to an enum?
I think that also means that we have to go from `iterable<XRJointSpace>` to `iterable<XRJointName, XRJointSpace>` in [XRHand](https://www.w3.org/TR/webxr-hand-input-1/#xrhand)

**Comment by domenic** [comment]
Yeah, an enum is probably the right call.

**Comment by domenic** [comment]
(Submitted too soon.)

Changing the iterable in the way you suggest sounds good. And that'd also allow you to remove the indexed getter (`getter XRJointSpace joint(unsigned long jointIndex)`), which uses the mostly-legacy IDL "fake array" feature, in favor of something more like `XRJointSpace get(XRJointName jointName)`.

Overall the end result seems a lot more webby. Do you think it'd work as well for your users?

**Comment by cabanier** [comment]
> Overall the end result seems a lot more webby. Do you think it'd work as well for your users?

I think so. I looked at the implementation of three.js and that would easily be upgraded.
Babylon.js might continue to work with the change.

**Comment by alice** [comment]
Please also consider moving away from the medical names during this process, per my comments in the TAG review.

**Comment by Manishearth** [comment]
This was discussed earlier: https://github.com/immersive-web/webxr-hand-input/issues/17

The main reason for this choice was that enums aren't easily extensible for future additions, with a slight performance argument around doing 50 string matches per frame. The numeric indices are also kinda necessary to map the ordering of results in the `getJointPoses()` API: We can totally just spec this numeric mapping and not expose it anywhere, but that doesn't seem as good.

As for using medical names: I've given some reasoning [here](https://github.com/w3ctag/design-reviews/issues/568#issuecomment-736898162), TLDR: numbers are pretty ambiguous and require a diagram anyway (because nobody is exposing _all_ joints), but the names are easier to remember than numbers (which may change from platform to platform).

**Comment by domenic** [comment]
> The main reason for this choice was that enums aren't easily extensible for future additions

In that case using `DOMString` would be fine.

**Comment by cabanier** [comment]
> The main reason for this choice was that enums aren't easily extensible for future additions

When will we ever add more joints? It seems an enum would work here.

**Comment by cabanier** [comment]
An issue with moving to `iterable<XRJointName, XRJointSpace>` is that `fillJointRadii` and `fillPoses` take a sequence of jointspaces. In the previous version this allowed us to pass an XRHand since it was array like.
Can we still do that or should we provide another function?

**Comment by domenic** [comment]
It's also not clear that hiding the error on older browsers by returning `null` is actually any better than eagerly throwing a TypeError, in such a situation.

If the code in question doesn't test for the failure case, then likely the next step will be to get a TypeError anyway, as it does something like `hand.joint("very-new-joint-name").addEventListener(...)` or passes `hand.joint("very-new-joint-name")` to an API that does not expect `null`.

If the code in question does test for the failure case, then we're discussing whether that code needs to use `try { } catch { }` or `if (joint === null) { }`, which isn't a huge difference.

> Can we still do that or should we provide another function?

You could stay with `iterable<XRJointSpace>`, and get that property. Or you could have something like `hand.allJoints()` or `hand.joints()`. I'm not sure what would be more intuitive for your users.

You could even move from `iterable<XRJointName, XRJointSpace>` to `readonly maplike<XRJointName, XRJointSpace>`. Then instead of `joint()` you would have `get()`, and instead of `allJoints()` you would have `values()`. You'd also get `keys()`, `entries()`, and `has()` for free. That seems a little weird though; I'm not sure if a web developer will really think of a hand as a map which you get entries, with the joint names being the keys and the joint spaces being the values. (I dunno though; not a domain expert!)

**Comment by cabanier** [comment]
> I guess it depends on whether you expect iteration code to often want to know the name of the joint alongside getting the `XRJointSpace`. (Although you could solve that by adding a `name` property to `XRJointSpace` itself, I suppose.)

They wouldn't need to know the name but they would expect them to be always returned in the same order.
If we stay with `iterable&lt;XRJointSpace&gt;' , can we define that the iteration has a certain order?

> That seems a little weird though; I'm not sure if a web developer will really think of a hand as a map which you get entries from, with the joint names being the keys and the joint spaces being the values. (I dunno though; not a domain expert!)

Yes, I envision a hand as a set list of joints.

**Comment by domenic** [comment]
> If we stay with `iterable<XRJointSpace>' , can we define that the iteration has a certain order?

For sure.

**Comment by Manishearth** [comment]
> When will we ever add more joints? It seems an enum would work here.

Yeah, I think the decision was clearer in the past when we hadn't fixed the number of joints. Now we still may end up adding more joints for polydactyl hands, but we can perhaps cross that bridge when we get to it.

-------

Maplike or `iterable<XRJoint>` seems fine to me: I don't have a strong preference. We may wish to add an `XRJointName` attribute to `XRJoint` though.

One thing to note is that we must still keep the joint-number mapping for `fillJointPoses()` to work.

/agenda to check with the group on this

**Comment by cabanier** [comment]
Thanks @Manishearth @domenic !
I created a PR with the changes discussed here. Feel free to comment!
