### ISSUE TITLE
Explainer Proposed IDL missing fillJointRadii and fillPoses

### ISSUE THREAD

**Issue by De-Panther** [immersive-web/webxr-hand-input#75]
I guess that
https://github.com/immersive-web/webxr-hand-input/blob/6ed92979a3217a1aa13343bd9c86435fbc5fe825/explainer.md
```
partial interface XRFrame {
    XRJointPose? getJointPose(XRJointSpace joint, XRSpace relativeTo);
}
```
Should be
```
partial interface XRFrame {
    XRJointPose? getJointPose(XRJointSpace joint, XRSpace relativeTo);
    boolean fillJointRadii(sequence<XRJointSpace> jointSpaces, Float32Array radii);
    boolean fillPoses(sequence<XRSpace> spaces, XRSpace baseSpace, Float32Array transforms);
}
```
Like in https://github.com/immersive-web/webxr-hand-input/blob/117b050d08fe607ac381a7d2585d11f0071ac71a/index.bs#L324

**Comment by Manishearth** [comment]
Yep. We actually need further fixes to the explainer, it's lagging the spec by a bit.
