### ISSUE TITLE
What does XRHand.get() return for unknown joint name?

### ISSUE THREAD

**Issue by takahirox** [immersive-web/webxr-hand-input#84]
`XRHand.get()` description is 

> The get(jointName) method when invoked on an XRHand this MUST run the following steps:
> 1. Let joints be the value of this's [[joints]] internal slot.
> 2. Return joints[jointName].

https://immersive-web.github.io/webxr-hand-input/#dom-xrhand-get

What does `XRHand.get()` return for unknown joint name? `Return joints[jointName]` implies it returns `undefined`? If so, I would like to suggest clarifying it. And returns `null` or throws an exception would be more natural as a method for me.

**Comment by Maksims** [comment]
Probably would argue against throwing an exception.
Classic JS Map returns `undefined` from `get` when there is no value defined. It feels natural.
Null usually implies that is "known key", and that it might change to something else.

**Comment by Manishearth** [comment]
It should return null

**Comment by takahirox** [comment]
Thanks for the comments. I would make a PR with `null` so far.

Let me know if `undefined` should be more proper to follow `Map` style. It would be easy to just replace the word `null` with `undefined` in the PR.

**Comment by Manishearth** [comment]
Yeah, sorry, `undefined` since we're maplike

**Comment by takahirox** [comment]
OK. So I would make a PR with `undefined`. `Return joints[jointName]` may imply so, but I think clarifying it would be good. Let me know if you think we don't need.
