### ISSUE TITLE
Spec should define the X axis of a joint. In addition Y axis seems incorrect

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-hand-input#89]
The spec is silent on the direction of the X axis, only Y and Z are defined.

This is creating issues with interoperability because OpenXR's coordinate system is different than WebXR's.
The [WebXR spec states](https://immersive-web.github.io/webxr/#xrreferencespace-interface):

> The native origin for every XRReferenceSpace describes a coordinate system where +X is considered "Right", +Y is considered "Up", and -Z is considered "Forward".

It seems that this is not the case for joint spaces. The Oculus browser treats joint spaces the same like all the other ones (and I believe Servo did as well since we had interoperability) but it seems that it needs to make an exception for joints which seems counterintuitive.
@Manishearth do you remember working around this issue?

**Comment by cabanier** [comment]
CC @fordacious

**Comment by Manishearth** [comment]
Defining Y and Z automatically defines X, WebXR is right-handed.

We're following the WebXR definition of the axes, the only fudge factor is what is the "standard" hand position used -- I think in this spec it is "palms down", giving a -Z forward and +Y up.
