### ISSUE TITLE
How do we name and pick parts of the skeleton to expose?

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-hand-input#9]
This came up in a discussion amongst OpenXR folks.

There are roughly, three ways of picking and naming skeleton points. For any given bone, we can pick:

 - the joint at the bottom of it
 - the joint at the top of it
 - some midpoint

for fixing the pose position, assuming one of the axes of orientation is parallel to the bone, and the other is perpendicular to the skin.

Each one of these techniques has a problem. Using the joint at the bottom means that you have to both make up a fake bone for the fingertips, and you also lose the ability to directly access the "pseudocarpal" bone between the metacarpal and the wrist. Note that it's totally possible to calculate all properties of this bone since its "position" will be the wrist position and its orientation will be the subtraction of the metacarpal and wrist. This seems cumbersome.

Using the joint at the top works out, however now you _have_ to expose some naming for the pseudocarpal bones. These don't actually exist, the carpal bones don't match up perfectly with each finger, but their range of motion is limited enough that it's easier to imagine them as bones individually connected to each metacarpal.

Using the bone midpoint is the worst of both worlds, you now have to name the pseudocarpal bones and you _also_ need a fake tip bone.

I've been talking with @yl-msft about the openxr design -- It had previously picked the "joint at the bottom" option, but it was inconsistent about this and had bugs around orientations where the orientation was parallel to the wrong bone.  We both seem to like the "joint at the top" option, despite the need for naming the pseudocarpal bone.

cc @Artyom17 thoughts?

**Comment by cabanier** [comment]
@Manishearth Is this still an issue?

**Comment by Manishearth** [comment]
Not really, we picked the same naming scheme as Microsoft and Oculus I think so we're good.
