### ISSUE TITLE
Missing definition of "force emulation"

### ISSUE THREAD

**Issue by jmajnert** [immersive-web/webxr-hand-input#94]
https://github.com/immersive-web/webxr-hand-input/blob/41f27aef0cdb494705523ac1960b444339a0127f/index.bs#L345

What is "force emulation" ? The spec is missing a definition or a reference.

**Comment by cabanier** [comment]
`force emulation` is one of the parameters passed to `populate the pose`.

**Comment by jmajnert** [comment]
Oh yeah, I forgot to close this one. My lack of understanding was caused by me reading the FPWD instead of ED :)
