### ISSUE TITLE
Unclear algorithm step

### ISSUE THREAD

**Issue by jmajnert** [immersive-web/webxr-hand-input#96]
https://github.com/immersive-web/webxr-hand-input/blob/41f27aef0cdb494705523ac1960b444339a0127f/index.bs#L345

The sentence "Populate the pose of joint in baseSpace at the time represented by frame into pose" is not clear. The dictionary gives "to populate something", not "to populate into something". The sentence should be rebuilt to clarify what is actually required here.

**Comment by jmajnert** [comment]
Same here: https://github.com/immersive-web/webxr-hand-input/blob/41f27aef0cdb494705523ac1960b444339a0127f/index.bs#L398

**Comment by cabanier** [comment]
`Populate the pose` links to a detailed algorithm in the WebXR spec. Are you saying that we should add a `to` to the beginning of the sentence?

**Comment by jmajnert** [comment]
Again, I was looking at FPWD. The ED does link to the algorithm that clarifies what it means. No changes needed. Closing task
