### ISSUE TITLE
Define behavior when null arguments are passed to algorithms

### ISSUE THREAD

**Issue by jmajnert** [immersive-web/webxr-hand-input#99]
I'm not sure we need to define this, but what should be the behavior of:
* getJointPose() when joint or baseSpace are null
* fillJointRadii() when jointSpaces is null, any of the spaces in jointSpaces is null or radii is null
* fillPoses() when spaces is null, any space in in spaces is null, baseSpace is null or transforms is null

**Comment by cabanier** [comment]
That is taken care of by WebIDL.
